"""empty message

Revision ID: 8a03f5672b58
Revises: 
Create Date: 2020-02-08 16:58:49.496863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a03f5672b58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TripStartAddress', sa.String(), nullable=True),
    sa.Column('TripStopAddress', sa.String(), nullable=True),
    sa.Column('LatLngStart', sa.String(), nullable=True),
    sa.Column('LatLngEnd', sa.String(), nullable=True),
    sa.Column('Dzongkha', sa.String(), nullable=True),
    sa.Column('AmbulanceNo', sa.String(), nullable=True),
    sa.Column('StartTime', sa.String(), nullable=True),
    sa.Column('EndTime', sa.String(), nullable=True),
    sa.Column('TripDuration', sa.String(), nullable=True),
    sa.Column('DistanceTravelled', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps')
    # ### end Alembic commands ###
